#!/bin/sh

rematrix_exec=$1
if [ -z "$rematrix_exec" ]; then
    echo $0 rematrix_exec
    exit 1
fi

make_image() {
    config=$1
    mode=$(echo $config | cut -d , -f 1)
    color_name=$(echo $config | cut -d , -f 2)
    char_color=$(echo $config | cut -d , -f 3)
    feeder_color=$(echo $config | cut -d , -f 4)
    bg_color=$(echo $config | cut -d , -f 5)
    $rematrix_exec -c $char_color -f $feeder_color ${bg_color:+-l $bg_color} -m $mode -r 15 &
    pid=$!
    sleep 40
    import -window root -crop 1920x$((1080 - 32))+0+32 $color_name-$mode.png
    kill $pid
    wait $pid
}

for mode in bin dna dec hex matrix; do
    make_image $mode,green,#4efd4e,#ffffff,#000000
done

for colors in black,#000000,#282828,#ffffff red,#cc241d,#fb4934, blue,#458588,#83a598,; do
    make_image matrix,$colors
done
